version: 2

jobs:
  "Backend":
    working_directory: ~/BackEnd/BackEnd
    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          
    steps:

      - checkout:
          path: ~/BackEnd

      - run:
          command: ls /home/circleci/BackEnd/

      - restore_cache:
          key: booking-sys-{{ checksum "~/BackEnd/BackEnd/pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: booking-sys-{{ checksum "~/BackEnd/BackEnd/pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/bookingsys-0.0.1.jar

      
  "Frontend":
    docker:
      - image: circleci/node:12.9.1-browsers
  
    working_directory: ~/FrontEnd/FrontEnd/majorproject-front-end
    steps:
      - checkout:
          path: ~/FrontEnd
      
      - run:
          command: ls /home/circleci/FrontEnd/FrontEnd/majorproject-front-end
      - save_cache:
          paths:
            - node_modules
            - ~/.npm 
            - ~/.cache

          key: v1-dependencies-{{ checksum "~/FrontEnd/FrontEnd/majorproject-front-end/package.json" }}
      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "~/FrontEnd/FrontEnd/majorproject-front-end/package.json" }}
            - v1-dependencies-
      
      - run: npm install
    
      - run: npm test



workflows:
  version: 2
  build:
    jobs:
      - "Backend"
      - "Frontend"
