version: '3'

services:
  react-front-end:
    image: react-front-end:1
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
